WITH TRANSPORTADORA AS ( SELECT ROW_NUMBER()  OVER ( ORDER BY SHIPPER_ID ) AS SK_TRANSPORTADORA -- CHAVE SURROGATE
                               ,SHIPPER_ID    AS ID_TRANSPORTADORA
					  		   ,COMPANY_NAME  AS NOME_TRANSPORTADORA
							   ,PHONE		  AS TELEFONE_TRANSPORTADORA
							FROM {{ source('northiwind_dados_brutos_stitch', 'shippers' )}} )
  SELECT * FROM TRANSPORTADORA